# Generated by Django 5.1.5 on 2025-02-16 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_favorite_recipe_alter_favorite_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='color',
        ),
    ]
