# Generated by Django 5.1.6 on 2025-02-16 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_subscription_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='', null=True, upload_to='users/avatars/', verbose_name='Аватар'),
        ),
    ]
