# Generated by Django 5.1.5 on 2025-02-20 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_avatar'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(condition=models.Q(('author', models.F('user')), _negated=True), name='no_self_subscription'),
        ),
    ]
